// ================================================================
// WORDS DATABASE — Imposter Game
// 150+ words with i.ibb.co image URLs [manually by mibsam]
// ================================================================

const WORDS = [

  // ── Animals ──────────────────────────────────────────────────
  { word: "Elephant",       category: "Animals",     image: "https://i.ibb.co/svhLf3HZ/x.jpg" },
  { word: "Tiger",          category: "Animals",     image: "https://i.ibb.co/yBBNbp8b/x.jpg" },
  { word: "Penguin",        category: "Animals",     image: "https://i.ibb.co/SXDT8mRj/x.jpg" },
  { word: "Dolphin",        category: "Animals",     image: "https://i.ibb.co/kv2snpL/x.jpg" },
  { word: "Giraffe",        category: "Animals",     image: "https://i.ibb.co/G4HPNv6Q/x.jpg" },
  { word: "Lion",           category: "Animals",     image: "https://i.ibb.co/C5CqrbJN/x.jpg" },
  { word: "Panda",          category: "Animals",     image: "https://i.ibb.co/xSY3V2Rm/x.jpg" },
  { word: "Shark",          category: "Animals",     image: "https://i.ibb.co/DHkZBshc/x.jpg" },
  { word: "Eagle",          category: "Animals",     image: "https://i.ibb.co/MDnRD7Gz/x.jpg" },
  { word: "Gorilla",        category: "Animals",     image: "https://i.ibb.co/yFjb0WnP/x.jpg" },
  { word: "Flamingo",       category: "Animals",     image: "https://i.ibb.co/WWBZH31Z/x.jpg" },
  { word: "Cheetah",        category: "Animals",     image: "https://i.ibb.co/mCNRxvZS/x.jpg" },
  { word: "Polar Bear",     category: "Animals",     image: "https://i.ibb.co/11P3nFW/x.jpg" },
  { word: "Chameleon",      category: "Animals",     image: "https://i.ibb.co/XxMpmPbX/x.jpg" },
  { word: "Octopus",        category: "Animals",     image: "https://i.ibb.co/HLqwhnSC/x.jpg" },
  { word: "Kangaroo",       category: "Animals",     image: "https://i.ibb.co/cSSpn5D9/x.jpg" },
  { word: "Parrot",         category: "Animals",     image: "https://i.ibb.co/LFSDBWT/x.jpg" },
  { word: "Wolf",           category: "Animals",     image: "https://i.ibb.co/c0FJWhQ/x.jpg" },
  { word: "Crocodile",      category: "Animals",     image: "https://i.ibb.co/RTJ5fjG2/x.jpg" },
  { word: "Peacock",        category: "Animals",     image: "https://i.ibb.co/pjX1CFgn/x.jpg" },

  // ── Food ─────────────────────────────────────────────────────
  { word: "Pizza",          category: "Food",        image: "https://i.ibb.co/99VjBS42/x.jpg" },
  { word: "Porotta",          category: "Food",        image: "https://i.ibb.co/hF2ZyQ1V/x.jpg" },
  { word: "Burger",         category: "Food",        image: "https://i.ibb.co/bgRfwBj6/x.jpg" },
  { word: "Apple",          category: "Food",        image: "https://i.ibb.co/d0KRYtxj/x.jpg" },
  { word: "Ice Cream",      category: "Food",        image: "https://i.ibb.co/6RDmH5g8/x.jpg" },
  { word: "Mango",          category: "Food",        image: "https://i.ibb.co/Qv0rDzPr/x.jpg" },
  { word: "Cake",           category: "Food",        image: "https://i.ibb.co/JWP7x1LF/x.jpg" },
  { word: "Noodles",          category: "Food",        image: "https://i.ibb.co/DPmB1HjN/x.jpg" },
  { word: "KFC",          category: "Food",        image: "https://i.ibb.co/hJ7XQpr6/x.jpg" },
  { word: "Oreo",      category: "Food",        image: "https://i.ibb.co/yn8XPpqd/x.jpg" },
  { word: "Donut",          category: "Food",        image: "https://i.ibb.co/k6DNFPjn/x.jpg" },
  { word: "Cupcake",      category: "Food",        image: "https://i.ibb.co/DPHRBLxb/x.jpg" },
  { word: "Strawberry",     category: "Food",        image: "https://i.ibb.co/354W1P53/x.jpg" },
  { word: "Watermelon",     category: "Food",        image: "https://i.ibb.co/6cxPphBn/x.jpg" },
  { word: "Popcorn",        category: "Food",        image: "https://i.ibb.co/whGVLH6c/x.jpg" },
  { word: "Lollipop",        category: "Food",        image: "https://i.ibb.co/yn2fWVbS/x.jpg" },
  { word: "Nutella",        category: "Food",        image: "https://i.ibb.co/84QN969J/x.jpg" },
  { word: "Cocacola",        category: "Food",        image: "https://i.ibb.co/1GwD61Ty/x.jpg" },
  { word: "Banana",        category: "Food",        image: "https://i.ibb.co/FL9NRBr2/x.jpg" },
  { word: "Chocolate",      category: "Food",        image: "https://i.ibb.co/sJPVrSsz/x.jpg" },
  { word: "Laddoo",       category: "Food",        image: "https://i.ibb.co/zhkzcGsP/x.jpg" },
  { word: "Pineapple",      category: "Food",        image: "https://i.ibb.co/zt5QcB4/x.jpg" },

  // ── Transport ────────────────────────────────────────────────
  { word: "Auto Rickshaw",       category: "Transport",   image: "https://i.ibb.co/bg9L206J/x.jpg" },
  { word: "Bicycle",        category: "Transport",   image: "https://i.ibb.co/cK48k1mP/x.jpg" },
  { word: "Train",     category: "Transport",   image: "https://i.ibb.co/Fb7fB6w0/x.jpg" },
  { word: "Ambulance",       category: "Transport",   image: "https://i.ibb.co/gLJ6Sd8q/x.jpg" },
  { word: "Scooter",          category: "Transport",   image: "https://i.ibb.co/JwwB4GfV/x.jpg" },
  { word: "Jeep",      category: "Transport",   image: "https://i.ibb.co/Y4bxzN3B/x.jpg" },
  { word: "Helicopter",     category: "Transport",   image: "https://i.ibb.co/bjGLfq5f/x.jpg" },
  { word: "Airplane",category: "Transport",   image: "https://i.ibb.co/j9sCdNrK/x.jpg" },
  { word: "Car",         category: "Transport",   image: "https://i.ibb.co/QvRD4s2F/x.jpg" },
  { word: "Fire Truck",        category: "Transport",   image: "https://i.ibb.co/YTKDDRpb/x.jpg" },
  { word: "Bike",     category: "Transport",   image: "https://i.ibb.co/6Jq0TXRs/x.jpg" },
  { word: "Boat",      category: "Transport",   image: "https://i.ibb.co/RTDn5Vqs/x.jpg" },
  { word: "Lorry",        category: "Transport",   image: "https://i.ibb.co/k2WYcG8N/x.jpg" },
  { word: "Rocket",     category: "Transport",   image: "https://i.ibb.co/zV3f6tXd/x.jpg" },

  // ── Nature ───────────────────────────────────────────────────
  { word: "Rainbow",        category: "Nature",      image: "https://i.ibb.co/8D3rZXN3/x.jpg" },
  { word: "Desert",      category: "Nature",      image: "https://i.ibb.co/5hPxhTrr/x.jpg" },
  { word: "Moon",        category: "Nature",      image: "https://i.ibb.co/Zp9RtCyf/x.jpg" },
  { word: "Earth",         category: "Nature",      image: "https://i.ibb.co/kgQqTm98/x.jpg" },
  { word: "Cactus",        category: "Nature",      image: "https://i.ibb.co/ynwqy5rt/x.jpg" },
  { word: "Rose",        category: "Nature",      image: "https://i.ibb.co/Q7c0df8j/x.jpg" },
  { word: "Rain",category: "Nature",      image: "https://i.ibb.co/35b31454/x.jpg" },
  { word: "Cloud",     category: "Nature",      image: "https://i.ibb.co/cXSzxjQQ/x.jpg" },
  { word: "Mushroom",         category: "Nature",      image: "https://i.ibb.co/Xx1rmr9S/x.jpg" },
  { word: "Sea",      category: "Nature",      image: "https://i.ibb.co/BxqQtSt/x.jpg" },
  { word: "Sun",      category: "Nature",      image: "https://i.ibb.co/WNhcX5hL/x.jpg" },
  { word: "Tree",       category: "Nature",      image: "https://i.ibb.co/hxZ6Mmhp/x.jpg" },
  { word: "Fire", category: "Nature",      image: "https://i.ibb.co/p6FV3NQ5/x.jpg" },
  { word: "Stone",      category: "Nature",      image: "https://i.ibb.co/VpgX2knF/x.jpg" },
  { word: "Thunder",       category: "Nature",      image: "https://i.ibb.co/jv436KnL/x.jpg" },

// ── Sports ───────────────────────────────────────────────────
  { word: "Cricket",            category: "Sports",      image: "https://i.ibb.co/4RdQH6vw/x.jpg" },
  { word: "Football",           category: "Sports",      image: "https://i.ibb.co/mrf9CDgP/x.jpg" },
  { word: "Carrom",             category: "Sports",      image: "https://i.ibb.co/yBys7f7h/x.jpg" },
  { word: "Ludo",               category: "Sports",      image: "https://i.ibb.co/m5d8z8XV/x.jpg" },
  { word: "Swimming",           category: "Sports",      image: "https://i.ibb.co/8nfnTVTj/x.jpg" },
  { word: "Running",            category: "Sports",      image: "https://i.ibb.co/FLJg1vhc/x.jpg" },
  { word: "Chess",              category: "Sports",      image: "https://i.ibb.co/Ndp8WD4F/x.jpg" },
  { word: "Cycling",            category: "Sports",      image: "https://i.ibb.co/G4Y3GNRH/x.jpg" },
  { word: "Snakes and Ladders", category: "Sports",      image: "https://i.ibb.co/NnpL5WTn/x.jpg" },
  { word: "Minecraft",          category: "Sports",      image: "https://i.ibb.co/zh97KPSt/x.jpg" },
  { word: "Roblox",             category: "Sports",      image: "https://i.ibb.co/67f2nkTv/x.jpg" },
  { word: "GTA 5",              category: "Sports",      image: "https://i.ibb.co/yc2cgHQz/x.jpg" },
  { word: "Subway Surfers",     category: "Sports",      image: "https://i.ibb.co/gb0RZ6Q7/x.jpg" },

  // ── Everyday Objects ─────────────────────────────────────────
  { word: "Camera",         category: "Objects",     image: "https://i.ibb.co/qLdhMR6Q/x.jpg" },
  { word: "Laptop",         category: "Objects",     image: "https://i.ibb.co/SDB0Qrk7/x.jpg" },
  { word: "Guitar",         category: "Objects",     image: "https://i.ibb.co/WZvp3j1/x.jpg" },
  { word: "Piano",          category: "Objects",     image: "https://i.ibb.co/TqrxDMC8/x.jpg" },
  { word: "Candle",         category: "Objects",     image: "https://i.ibb.co/hJLz5wcw/x.jpg" },
  { word: "Umbrella",       category: "Objects",     image: "https://i.ibb.co/hRWZ6300/x.jpg" },
  { word: "Diamond",        category: "Objects",     image: "https://i.ibb.co/GvdP7rSv/x.jpg" },
  { word: "Scissors",       category: "Objects",     image: "https://i.ibb.co/BVt63tvD/x.jpg" },
  { word: "Kite",           category: "Objects",     image: "https://i.ibb.co/wV2QPzj/x.jpg" },
  { word: "Trophy",         category: "Objects",     image: "https://i.ibb.co/Tx8jGC4h/x.jpg" },
  { word: "Mobile Phone",   category: "Objects",     image: "https://i.ibb.co/4RVgZnGJ/x.jpg" },
  { word: "Television",     category: "Objects",     image: "https://i.ibb.co/JjdsnXhW/x.jpg" },
  { word: "Shoes",          category: "Objects",     image: "https://i.ibb.co/XZbrx0Hj/x.jpg" },
  { word: "Mirror",         category: "Objects",     image: "https://i.ibb.co/B29k7xtR/x.jpg" },
  { word: "Newspaper",      category: "Objects",     image: "https://i.ibb.co/jvSkcrP1/x.jpg" },
  { word: "Bucket",         category: "Objects",     image: "https://i.ibb.co/V0tzBR8W/x.jpg" },
  { word: "Fan",            category: "Objects",     image: "https://i.ibb.co/rf7M65p5/x.jpg" },
  { word: "Bulb",           category: "Objects",     image: "https://i.ibb.co/0jyTsrzv/x.jpg" },
  { word: "Coin",           category: "Objects",     image: "https://i.ibb.co/HfZfR9nn/x.jpg" },
  { word: "Soap",           category: "Objects",     image: "https://i.ibb.co/FbRpYCFv/x.jpg" },
  { word: "Torch",          category: "Objects",     image: "https://i.ibb.co/DPGHGFBR/x.jpg" },
  { word: "Toothbrush",     category: "Objects",     image: "https://i.ibb.co/PGZCQfzd/x.jpg" },
  { word: "Spoon",          category: "Objects",     image: "https://i.ibb.co/35gy42Lm/x.jpg" },
  { word: "Chair",        category: "Objects",     image: "https://i.ibb.co/Q31DXWbd/x.jpg" },

// ── School Stationery ────────────────────────────────────────
  { word: "Pencil",         category: "Stationery",  image: "https://i.ibb.co/0jjcqbgD/x.jpg" },
  { word: "Pen",            category: "Stationery",  image: "https://i.ibb.co/nMVsfwDk/x.jpg" },
  { word: "Eraser",         category: "Stationery",  image: "https://i.ibb.co/5xhnKjvH/x.jpg" },
  { word: "Sharpener",      category: "Stationery",  image: "https://i.ibb.co/9Hn6084w/x.jpg" },
  { word: "Scale",          category: "Stationery",  image: "https://i.ibb.co/h1gzpYpW/x.jpg" },
  { word: "Notebook",       category: "Stationery",  image: "https://i.ibb.co/S4SV6z7j/x.jpg" },
  { word: "Crayon",         category: "Stationery",  image: "https://i.ibb.co/SDRp3sRS/x.jpg" },
  { word: "Glue",           category: "Stationery",  image: "https://i.ibb.co/rRPTh1VL/x.jpg" },
  { word: "Water Bottle",   category: "Stationery",  image: "https://i.ibb.co/4wgV5dB2/x.jpg" },

  // ── Professions ──────────────────────────────────────────────
  { word: "Doctor",         category: "Professions", image: "https://i.ibb.co/0y4gVzpG/x.jpg" },
  { word: "Police",         category: "Professions", image: "https://i.ibb.co/m5XxM8s0/x.jpg" },
  { word: "Teacher",        category: "Professions", image: "https://i.ibb.co/MkCJtVMy/x.jpg" },
  { word: "Soldier",        category: "Professions", image: "https://i.ibb.co/m5rkG9Cs/x.jpg" },
  { word: "Astronaut",      category: "Professions", image: "https://i.ibb.co/PvFjjS7K/x.jpg" },
  { word: "Farmer",         category: "Professions", image: "https://i.ibb.co/wFGLfj5d/x.jpg" },
  { word: "Barber",         category: "Professions", image: "https://i.ibb.co/dscS3H7V/x.jpg" },
  { word: "Cook",      category: "Professions", image: "https://i.ibb.co/99DrV3jk/x.jpg" },

  // ── Body Parts ───────────────────────────────────────────────
  { word: "Eyes",           category: "Body Parts",  image: "https://i.ibb.co/j9Bd29V9/x.jpg" },
  { word: "Ears",           category: "Body Parts",  image: "https://i.ibb.co/tMw1g8Tv/x.jpg" },
  { word: "Nose",           category: "Body Parts",  image: "https://i.ibb.co/4R2vdgj3/x.jpg" },
  { word: "Mouth",          category: "Body Parts",  image: "https://i.ibb.co/BKfXg2pD/x.jpg" },
  { word: "Hands",          category: "Body Parts",  image: "https://i.ibb.co/hJ0JsqKY/x.jpg" },
  { word: "Legs",           category: "Body Parts",  image: "https://i.ibb.co/whjkcM6M/x.jpg" },
  { word: "Teeth",          category: "Body Parts",  image: "https://i.ibb.co/Pz6j3fz6/x.jpg" },
  { word: "Tongue",         category: "Body Parts",  image: "https://i.ibb.co/bjKxkPHh/x.jpg" },
  { word: "Hair",           category: "Body Parts",  image: "https://i.ibb.co/7JfY5fhL/x.jpg" },
  { word: "Finger",        category: "Body Parts",  image: "https://i.ibb.co/Dg8GjcZN/x.jpg" },

  // ── Random Items ─────────────────────────────────────────────
  { word: "Dragon",         category: "Random",      image: "https://i.ibb.co/G4QH6cFQ/x.jpg" },
  { word: "Robot",          category: "Random",      image: "https://i.ibb.co/GfVrzby5/x.jpg" },
  { word: "Drone",          category: "Random",      image: "https://i.ibb.co/S4gLLs9f/x.jpg" },
  { word: "Calculator",     category: "Random",      image: "https://i.ibb.co/35RZztGd/x.jpg" },
  { word: "Watch",          category: "Random",      image: "https://i.ibb.co/Tqxb11SJ/x.jpg" },
  { word: "Teddy",          category: "Random",      image: "https://i.ibb.co/22Hxy7B/x.jpg" },
  { word: "Mask",           category: "Random",      image: "https://i.ibb.co/84rrXVfX/x.jpg" },
  { word: "Helmet",         category: "Random",      image: "https://i.ibb.co/TxWtqnhs/x.jpg" },
  { word: "Ring",           category: "Random",      image: "https://i.ibb.co/vC1kfdKL/x.jpg" },
  { word: "Bag",            category: "Random",      image: "https://i.ibb.co/nNTkq9F9/x.jpg" },
  { word: "Key",            category: "Random",      image: "https://i.ibb.co/27gtQXhB/x.jpg" },
  { word: "Comb",           category: "Random",      image: "https://i.ibb.co/5XMRz5Wy/x.jpg" },
  { word: "Balloon",        category: "Random",      image: "https://i.ibb.co/VWhv80Zs/x.jpg" },
  { word: "Bell",           category: "Random",      image: "https://i.ibb.co/RkCxsLCT/x.jpg" },
  { word: "Charger",         category: "Random",      image: "https://i.ibb.co/k22zGJcz/x.jpg" },
  { word: "Ladder",         category: "Random",      image: "https://i.ibb.co/SDR85NDN/x.jpg" },


];

// Sanity check
console.log(`📚 Words loaded: ${WORDS.length}`);
